INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Mass Effect is a military science fiction media franchise created by Casey Hudson. The franchise depicts a distant future where humanity and several alien civilizations have colonized the galaxy using technology left behind by advanced precursor civilizations.', 'The franchise originated in a series of video games developed by BioWare and published by Electronic Arts. Each installment is a third-person shooter with role-playing elements. The first three games form a trilogy in which the player character, Commander Shepard, attempts to save the Milky Way galaxy from a race of ancient, hibernating machines known as the Reapers. The inaugural video game in the series, Mass Effect (2007), follows Shepards investigation of Saren Arterius, one of the Reapers agents. Mass Effect 2 (2010) begins two years later and sees Shepards forces battling the Collectors, an alien race abducting human colonies to facilitate the Reapers return. The original trilogys final installment, Mass Effect 3 (2012), depicts a war between the Reapers and the rest of the galaxy. A fourth game, Mass Effect: Andromeda (2017), featured a new setting and cast of characters, and a fifth is in active development.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive', 'Red Dead Redemption 2[a] is a 2018 action-adventure game developed and published by Rockstar Games. The game is the third entry in the Red Dead series and a prequel to the 2010 game Red Dead Redemption. The story is set in a fictionalized representation of the United States in 1899 and follows the exploits of outlaw Arthur Morgan, a member of the Van der Linde gang, who must deal with the decline of the Wild West whilst attempting to survive against government forces, rival gangs, and other adversaries. The game is presented through first- and third-person perspectives, and the player may freely roam in its interactive open world. Gameplay elements include shootouts, robberies, hunting, horseback riding, interacting with non-player characters, and maintaining the characters honor rating through moral choices and deeds. A bounty system governs the response of law enforcement and bounty hunters to crimes committed by the player.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'The Witcher 3: Wild Hunt[b] is a 2015 action role-playing game developed and published by CD Projekt. It is the sequel to the 2011 game The Witcher 2: Assassins of Kings and the third game in The Witcher video game series, played in an open world with a third-person perspective. The games follow The Witcher series of fantasy novels written by Andrzej Sapkowski.', 'The game takes place in a fictional fantasy world based on Slavic mythology. Players control Geralt of Rivia, a monster slayer for hire known as a Witcher, and search for his adopted daughter, who is on the run from the otherworldly Wild Hunt. Players battle the games many dangers with weapons and magic, interact with non-player characters, and complete quests to acquire experience points and gold, which are used to increase Geralts abilities and purchase equipment. The games story has three possible endings, determined by the players choices at key points in the narrative.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Set in a reimagining of 1500s Sengoku era Japan. An unnamed shinobi, tasked with protecting a young lord of mystical lineage, who is left for dead when a powerful samurai attacks and chops off his arm.', 'Sekiro: Shadows Die Twice[a] is a 2019 action-adventure game developed by FromSoftware and published by Activision. It was released for PlayStation 4, Windows, and Xbox One in March 2019, and for Stadia in October 2020. The game follows a shinobi known as Wolf, who attempts to take revenge on a samurai clan that imprisoned him and kidnapped his lord. The gameplay is focused on stealth, exploration, and combat, with a particular emphasis on boss battles. It takes place in a fictionalized Japan during the Sengoku period and makes strong references to Buddhist mythology and philosophy.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Set in 1274 on the Tsushima Island, the last samurai, Jin Sakai, must master a new fighting style, the way of the Ghost, to defeat the Mongol forces and fight for the freedom and independence of Japan.', 'The year is 1274. Samurai warriors are the legendary defenders of Japan, until the fearsome Mongol Empire invades the island of Tsushima, wreaking havoc and conquering the local population. As one of the last surviving samurai, you rise from the ashes to fight back. But, honorable tactics wont lead you to victory. You must move beyond your samurai traditions to forge a new way of fighting - the way of the Ghost -as you wage an unconventional war for the freedom of Japan.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'The player controls Mario on his quest to save Princess Peach and Dinosaur Land from the series antagonist Bowser and the Koopalings. The gameplay is similar to that of earlier Super Mario games: players control Mario through a series of levels in which the goal is to reach the goalpost at the end.', 'The plot of Super Mario World is detailed in the instruction booklet.[25] After bringing peace to the Mushroom World in Super Mario Bros. 3, the brothers Mario and Luigi decide to go on vacation with Princess Toadstool to a place called Dinosaur Land, a prehistoric-themed world swarming with dinosaurs and other enemies. While resting on the beach, Princess Toadstool is captured by Bowser. When Mario and Luigi wake up, they try to find her and, after hours of searching, come across a giant egg in the forest. It suddenly hatches and out of it comes a young dinosaur named Yoshi, who tells them his dinosaur friends have also been imprisoned in eggs by Bowsers kids, the evil Koopalings. Mario and Luigi soon realise that Bowsers forces must have captured Toadstool as well. Mario, Luigi and Yoshi set out to save Toadstool and Yoshis dinosaur friends, traversing through Dinosaur Land for Bowser and his Koopalings. To aid him, Yoshi gives Mario a cape as they begin their journey.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');

INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (game_list_id, game_id, position) VALUES (2, 10, 4);